### ISSUE TITLE
When dividing numbers, use highest precision when dividing?

### ISSUE THREAD

**Issue by abrkn** [defunctzombie/num#6]
1 / 10.00 could result in 0.10 and 1.00 / 10 likewise. Right now 1 / 100.000 = 0

**Comment by defunctzombie** [comment]
This is expected behavior because your numerator does not have enough precision. Imagine the case where you do `1/3`. If you want the result to be 0.10 you need to do `1.00/10.00`

**Comment by abrkn** [comment]
Fair enough. (I guess you can remove the TODO from the relevant unit test, then. It says something like "How should this work?")
