### ISSUE TITLE
invalid result for 12/1.1

### ISSUE THREAD

**Issue by jcollum-hcg** [defunctzombie/num#9]
```
coffee> d = num(1.1)
{ _int: { _s: 0, _d: [ 1, 1 ] },
  _precision: 1 }
coffee> n = num(12) 
{ _int: { _s: 0, _d: [ 1, 2 ] },
  _precision: 0 }
coffee> n.div(d) 
{ _int: { _s: 0, _d: [ 1, 0 ] },
  _precision: 0 }
```

It looks like the result of 12/1.1 is 10. Even vanilla js is better than that: 

```
coffee> 12.0/1.1
10.909090909090908
```

True answer is 

```
10.909090909090909090909090909090909090909090909090909
```

Of course that kind of precision is a bit much to expect out of js but I'd expect this library to be at least better than vanilla js. I see that the div op is dependent on the precision of the numerator but adding decimal points `n = num(12.0000)` didn't change anything. 

If this library isn't being worked on (it appears that it isn't) you should put a disclaimer on the Readme.

**Comment by defunctzombie** [comment]
Relax bro. This has nothing to do with vanilla js or library not being worked on and everything to do with precision and understanding how division works in this large number library. Division operator uses the precision of the numerator to determine how much precision will be in the result. In your case `n` has no precision (no digits after the decimal). The following works just fine.

``` js
var n = num('12.000');
var d = num('1.1');
n.div(d); // => 10.909
```

Or you can manually bump the precision of the numerator after you create it.

In fact the true answer is none of the ones you show because `.90909` just keeps repeating forever.

**Comment by jcollum-hcg** [comment]
Yeah but I think you can find a better way to deal with the example I gave: 

```
coffee> d = num('1.1');
{ _int: { _s: 0, _d: [ 1, 1 ] },
  _precision: 1 }
coffee> n = num(12.000);
{ _int: { _s: 0, _d: [ 1, 2 ] },
  _precision: 0 }
coffee> n.div(d);
{ _int: { _s: 0, _d: [ 1, 0 ] },
  _precision: 0 }
```

Converting a number to a string to get the desired precision is weird and unintuitive.

**Comment by defunctzombie** [comment]
I agree it is weird, but `12.000` is just `12` and carries no precision information. Without you specifying more info, there is just no great way to go about this. We could pick a random precision but then someone will complain about that.

**Comment by jcollum-hcg** [comment]
Maybe just adding something with more detail to the readme about precision would help. Also when you use an `_` prefix on a variable you're implying that it is sorta "not for general use".

**Comment by jcollum-hcg** [comment]
In case you don't believe me: 

> In Javascript there are no modifiers for object property accessing. The regular underscore sign is used by programmers as an initial character in the name of a given property, to indicate that the **user of the code is not advised to manipulate this property because in case of doing so, they might disturb the correct function of the program.** In other words, the underscore sign at the beginning is a pseudo emulation of the "private" modifier.

http://coderkeen.com/old/articles/identifiers-en.html#underscore

First google result.

**Comment by defunctzombie** [comment]
Yea, readme should use some love. I thought `set_precision` (https://github.com/defunctzombie/node-num/blob/master/num.js#L79) was documented, guess not.

Yes, those variables are not meant for you to mess with directly.
